# Generated by Django 5.0.6 on 2024-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=60)),
                ('name', models.TextField()),
                ('password', models.CharField(max_length=60)),
                ('dob', models.IntegerField()),
                ('usr_adr', models.CharField(max_length=60)),
                ('land_adr', models.CharField(max_length=60)),
            ],
        ),
    ]
