# Generated by Django 5.0.6 on 2024-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='land_adr',
        ),
        migrations.RemoveField(
            model_name='usr',
            name='usr_adr',
        ),
        migrations.AlterField(
            model_name='usr',
            name='dob',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usr',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usr',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usr',
            name='usrname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
