# Generated by Django 5.0.6 on 2024-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usr_land_adr_remove_usr_usr_adr_alter_usr_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='phoneno',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='usr',
            name='phoneverified',
            field=models.BooleanField(default=False),
        ),
    ]
