# Generated by Django 5.0.6 on 2024-06-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usr_phoneno_usr_phoneverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='phoneno',
            field=models.CharField(default='010', max_length=11),
        ),
    ]
