# Generated by Django 5.0.6 on 2024-06-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
    ]
