# Generated by Django 5.0.6 on 2024-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='announcement', max_length=50),
        ),
    ]
